### ISSUE TITLE
Fails to build with jsoncpp-1.8.4 (clang compiler)

### ISSUE THREAD

**Issue by yurivict** [PDAL/PDAL#1866]
```
/usr/bin/c++  -DHAVE_PYTHON=1 -DPDAL_PYTHON_LIBRARY=\"/usr/local/lib/libpython2.7.so\" -DUNIX -I/wrkdirs/usr/ports/math/pdal/work/PDAL-1.6/vendor/gtest/include -I/wrkdirs/usr/ports/math/pdal/work/PDAL-1.6/vendor/gtest -I/wrkdirs/usr/ports/math/pdal/work/PDAL-1.6 -isystem /usr/local/include -isystem /usr/local/include/python2.7 -isystem /usr/local/lib/python2.7/site-packages/numpy/core/include -O2 -pipe -fstack-protector -fno-strict-aliasing  -D_GLIBCXX_USE_C99 -O2 -pipe -fstack-protector -fno-strict-aliasing  -D_GLIBCXX_USE_C99   -std=c++11 -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wpointer-arith -Wcast-align -Wcast-qual -Wredundant-decls -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -MD -MT dimbuilder/CMakeFiles/dimbuilder.dir/DimBuilder.cpp.o -MF dimbuilder/CMakeFiles/dimbuilder.dir/DimBuilder.cpp.o.d -o dimbuilder/CMakeFiles/dimbuilder.dir/DimBuilder.cpp.o -c /wrkdirs/usr/ports/math/pdal/work/PDAL-1.6/dimbuilder/DimBuilder.cpp
/wrkdirs/usr/ports/math/pdal/work/PDAL-1.6/dimbuilder/DimBuilder.cpp:179:17: error: no viable conversion from 'void' to 'Json::Value'
    Json::Value name = dim.removeMember("name");
                ^      ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by abellgithub** [comment]
This has already been fixed in master.

**Comment by abellgithub** [comment]
Sorry for this problem.  Jsoncpp changed their interface :(  We package a copy of jsoncpp with PDAL that will be used if one isn't found.  If you remove (or rename) the existing jsoncpp library on your system, at least temporarily, PDAL should build.

We're planning on a release this week or next.
