### ISSUE TITLE
Arbiter compilation terminates

### ISSUE THREAD

**Issue by mbandy** [PDAL/PDAL#1507]
Hi! Trying to compile on Ubuntu 14.04 and this happens. Any ideas? Thanks!

```
[  6%] Building CXX object vendor/arbiter/CMakeFiles/pdal_arbiter.dir/arbiter.cpp.o                                 
/home/inti/software/PDAL/vendor/arbiter/arbiter.cpp: In constructor `pdal::arbiter::Time::Time(const string&, const string&)':                                                                                                   
/home/inti/software/PDAL/vendor/arbiter/arbiter.cpp:3883:11: error: `get_time' is not a member of `std'      
     ss >> std::get_time(&tm, format.c_str());                                                                      
           ^                                                                                                        
/home/inti/software/PDAL/vendor/arbiter/arbiter.cpp: In member function `std::string pdal::arbiter::Time::str(const string&) const':                                                                                             
/home/inti/software/PDAL/vendor/arbiter/arbiter.cpp:3896:11: error: `put_time' is not a member of `std'      
     ss << std::put_time(std::gmtime(&m_time), format.c_str());                                                     
           ^                                                                                                        
make[2]: *** [vendor/arbiter/CMakeFiles/pdal_arbiter.dir/arbiter.cpp.o] Error 1                                     
make[1]: *** [vendor/arbiter/CMakeFiles/pdal_arbiter.dir/all] Error 2                                               
make: *** [all] Error 2  
```

**Comment by mbandy** [comment]
It appears to be a g++ version issue. I updated to g++-5 and it compiles fine. It might be a good idea to mention this as a dependency for compilation.

I used this cmake command sucessfully.

`cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_CC_COMPILER=gcc-5`

**Comment by abellgithub** [comment]
Do you know what version you were using before?

**Comment by mbandy** [comment]
It was 4.8.4, now 5.4.1.

**Comment by abellgithub** [comment]
Seems we hit the one thing that was missing recently.  We may back out the change.  Still lots of people using G++ v4.  Sorry I didn't back to you sooner.

**Comment by mbandy** [comment]
No worries. Thanks!

**Comment by connormanning** [comment]
This should be fixed with 2693971, supporting G++ v4.
