### ISSUE TITLE
Can't compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by mbandy** [PDAL/PDAL#1493]
I am not very fluent in C++, so I ask for your patience. 

I am trying to compile PDAL 1.04 on Ubuntu 14.04. Compilation fails with the following at BpfCompressor.cpp.o. I have tried with g++ and clang++ and get the same error. 

Any ideas? Thanks in advance! I am already using the docker install sucessfully, but would like native build that is more scriptable and can take advantage of multiple processors. I have compiled 1.1 successfully, but I need some of the newer functionality.
```
[  3%] Built target pdal_boost
[  5%] Built target pdal_util
[  5%] Built target dimbuilder
[  6%] Built target generate_dimension_hpp
[  6%] Built target pdal_arbiter
[  6%] Building CXX object CMakeFiles/pdal_base.dir/io/BpfCompressor.cpp.o
In file included from /home/inti/PDAL/io/BpfCompressor.cpp:35:
/home/inti/PDAL/io/BpfCompressor.hpp:49:32: error: expected class name
    struct error : public std::runtime_error
                               ^
/home/inti/PDAL/io/BpfCompressor.hpp:51:46: error: member initializer 'runtime_error' does not name a non-static
      data member or base class
        error(const std::string& err) : std::runtime_error(err)
                                             ^~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/pdal_base.dir/io/BpfCompressor.cpp.o] Error 1
make[1]: *** [CMakeFiles/pdal_base.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by hobu** [comment]
Probably just need a 

```
#include <stdexcept>
```

in BpfCompressor.hpp.

The exception stuff was recently refactored, and #include ordering is not always the same.

**Comment by mbandy** [comment]
Thank you! I am a little embarrassed I couldn't come up with that myself. It worked and is now compiling happily.

**Comment by hobu** [comment]
We still will need to fix this though. Thanks for the report!

**Comment by connormanning** [comment]
Fixed via #1489.
