### PR TITLE
Update ArrowWriter.cpp to work with Arrow 21.0.0

### PR DESCRIPTION
**Pull request by amoeba**
This call to NewRowGroup was deprecated in Arrow 19.0.0 because the implementation wasn't using it,

https://github.com/apache/arrow/issues/45048

The deprecated variant of NewRowGroup was removed in Arrow 21.0.0:

https://github.com/apache/arrow/issues/46132

so this change will make PDAL compile cleanly against Arrow 21.0.0.

See https://github.com/Homebrew/homebrew-core/pull/230431.

### CODE REVIEW

**Comment by hobu** [comment]
2.9.1 with this fix will hopefully be released end of next week or first week of August. Thanks for the patch!

**Comment by amoeba** [comment]
Thanks @hobu.

**Comment by hobu** [comment]
```
/home/runner/work/PDAL/PDAL/plugins/arrow/io/ArrowWriter.cpp: In member function 'void pdal::ArrowWriter::flushBatch()':
/home/runner/work/PDAL/PDAL/plugins/arrow/io/ArrowWriter.cpp:526:55: error: no matching function for call to 'parquet::arrow::FileWriter::NewRowGroup()'
  526 |         auto result = m_parquetFileWriter->NewRowGroup();
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /home/runner/work/PDAL/PDAL/plugins/arrow/io/ArrowWriter.cpp:54:
/home/runner/work/PDAL/PDAL/.pixi/envs/dev/include/parquet/arrow/writer.h:92:27: note: candidate: 'virtual arrow::Status parquet::arrow::FileWriter::NewRowGroup(int64_t)'
   92 |   virtual ::arrow::Status NewRowGroup(int64_t chunk_size) = 0;
      |                           ^~~~~~~~~~~
```

I guess we'll need some kind of #ifdef or something to use the older prototype.
