### ISSUE TITLE
Python3- Importing pdal

### ISSUE THREAD

**Issue by slipperysaxophone** [PDAL/PDAL#1739]
I'm trying to get pdal to work with python 3.5+ and having no luck.

If I compile pdal from source:
- when i get to python3 setup.py build stage, i get an error compiling against numpy [cython.txt](https://github.com/PDAL/PDAL/files/1549073/cython.txt)
- If instead, I use pip3 to install the python/pdal bindings, the package has conflicting versions ' Version mismatch. PDAL Python support was compiled against version 2.x but setup is running version is 3.x. '

I have a basic docker [simple-docker.txt](https://github.com/PDAL/PDAL/files/1549021/simple-docker.txt) that does the bare minimum that i'd expect to be compatible with requirements from https://pypi.python.org/pypi/PDAL (PDAL 1.5, python 3.6.3). It also produces the 2.x vs 3.x error.

I also have a more complicated dockerfile that builds PDAL against python 3, and uses setup.py in PDAL/python to attempt to build.  [pdal-build-python3-dockerfile.txt](https://github.com/PDAL/PDAL/files/1549070/pdal-build-python3-dockerfile.txt)

Is there something obvious i'm missing?

**Comment by hobu** [comment]
The Python extension must be compiled against the same Python version that PDAL itself was compiled against. That is why you're (rightly) getting the error in the second bullet.

I have tested against Python 3.6 (on windows even!) but the error message you're seeing 
```
pdal/libpdalpython.cpp: In function 'PyObject* PyInit_libpdalpython()':
/usr/lib/python3/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1532:144: error: return-statement with no value, in function returning 'PyObject* {aka _object*}' [-fpermissive]
 #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
```
Would seem to imply some kind of mix up between Python 2.x and 3.x Cython output. `import_array` is different for numpy for both of these Pythons (version 3.x has a return value IIRC). Can you check the manual regeneration of the cython output?

**Comment by hobu** [comment]
After some further investigation, this error is caused by a bug in Cython for the Ubuntu version of Python that @slipperysaxophone was using. Simply upgrading the Cython `pip3 install cython --upgrade` cured the issue.

**Comment by mccarthyryanc** [comment]
I've hit this same error with Python 3.6, numpy 1.14 and Cython 0.27.3. All of this is running under a conda environment in Ubuntu 16.04, but it looks like all the paths are set properly: [python_build_error.txt](https://github.com/PDAL/PDAL/files/1733146/python_build_error.txt)
