### ISSUE TITLE
compile error: missing binary operator before token "("

### ISSUE THREAD

**Issue by vvovvo** [PDAL/PDAL#1842]
I got `missing binary operator before token "("` when running `make`. `cmake` successfully completed but it stuck at the `make` step. Any suggestion will be appreciated.

It is on a Ubuntu 14.04, GNU Make 3.18, cmake version 3.11.0-rc3.
Details of the error:
```
vv@pggis:~/pdal/build$ make 
Scanning dependencies of target pdal_boost
[  0%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/system/src/error_code.cpp.o
[  0%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/codecvt_error_category.cpp.o
[  0%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/operations.cpp.o
[  1%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/path.cpp.o
[  1%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/path_traits.cpp.o
[  1%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/portability.cpp.o
[  2%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/unique_path.cpp.o
[  2%] Building CXX object vendor/pdalboost/CMakeFiles/pdal_boost.dir/libs/filesystem/src/utf8_codecvt_facet.cpp.o
[  2%] Linking CXX static library ../../lib/libpdal_boost.a
[  2%] Built target pdal_boost
Scanning dependencies of target pdal_util
[  2%] Building CXX object pdal/util/CMakeFiles/pdal_util.dir/Bounds.cpp.o
[  2%] Building CXX object pdal/util/CMakeFiles/pdal_util.dir/Charbuf.cpp.o
[  3%] Building CXX object pdal/util/CMakeFiles/pdal_util.dir/FileUtils.cpp.o
[  3%] Building CXX object pdal/util/CMakeFiles/pdal_util.dir/Georeference.cpp.o
[  3%] Building CXX object pdal/util/CMakeFiles/pdal_util.dir/Utils.cpp.o
/home/vv/pdal/pdal/util/Utils.cpp:47:18: error: missing binary operator before token "("
 #if __has_include(<execinfo.h>)
                  ^
/home/vv/pdal/pdal/util/Utils.cpp:608:18: error: missing binary operator before token "("
 #if __has_include(<execinfo.h>)
                  ^
make[2]: *** [pdal/util/CMakeFiles/pdal_util.dir/Utils.cpp.o] Error 1
make[1]: *** [pdal/util/CMakeFiles/pdal_util.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by abellgithub** [comment]
You're going to need GCC 5. Install it or upgrade to Ubuntu 16.04.

Perhaps easier, you could also remove the __has_include directives around those header files, since they exist on your platform.

**Comment by abellgithub** [comment]
I changed the code and checked that it builds with GCC 4.8 on Ubuntu 14.04. I'd still recommend getting an up-to-date compiler if you're going to build things from source. Hope that helps.

**Comment by vvovvo** [comment]
That's greatly helpful! Much thanks.

**Comment by qiongqiong520** [comment]
i changed the code and checked that itbuildwithgcc4.8 on ubuntu 14.04 .I'd stillrecommendgetting an up-to-date compiler if you 're going to build things from source .Hope that helps.
meet the same problem.

**Comment by manmeet3591** [comment]
> i changed the code and checked that itbuildwithgcc4.8 on ubuntu 14.04 .I'd stillrecommendgetting an up-to-date compiler if you 're going to build things from source .Hope that helps.
> meet the same problem.

Thank you very much. Using an up-to-date compiler worked.
