### ISSUE TITLE
PDAL master doesn't build with GDAL 2.4.2 on Ubuntu 19.10

### ISSUE THREAD

**Issue by adamsteer** [PDAL/PDAL#2933]
PDAL pulled from the master branch (at #6617727) doesn't compile on Ubuntu Eoan (19.10) with GDAL 2.4.2.

```
git pull git@github.com:PDAL/PDAL.git
mkdir pdal-build && cd pdal-build
cmake ../PDAL
make -j8
```
(no flags) stops at:

```
...
...
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/pdal/SrsBounds.cpp.o
[ 40%] Building CXX object CMakeFiles/pdal_base.dir/pdal/Stage.cpp.o
PDAL/pdal/SpatialReference.cpp: In member function ‘std::vector<int> pdal::SpatialReference::getAxisOrdering() const’:
/build/PDAL/pdal/SpatialReference.cpp:360:29: error: ‘class OGRSpatialReference’ has no member named ‘GetDataAxisToSRSAxisMapping’
  360 |     output = current.get()->GetDataAxisToSRSAxisMapping();
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/pdal_base.dir/build.make:1805: CMakeFiles/pdal_base.dir/pdal/SpatialReference.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/pdal_base.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

```

with:

```
gdalinfo --version
GDAL 2.4.2, released 2019/06/28
cmake --version
cmake version 3.13.4
```
I understand work is proceeding on supporting GDAL 2.4+ and also GDAL 3.x, hoping this report helps.

**Comment by hobu** [comment]
Fixed 5f4e56af4d481ea93ca8179c56a00b11d6b8618d
