### ISSUE TITLE
2.4.2 doesn't build on MacOS < 10.15

### ISSUE THREAD

**Issue by 3nids** [PDAL/PDAL#3801]
Here are some of the errors:

```
/opt/QGIS/qgis-deps-dev/build/pdal/PDAL-2.4.2-src/pdal/util/FileUtils.cpp:205:16: error: 'exists' is unavailable: introduced in macOS 10.15
    return fs::exists(toNative(dirname));
               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:1986:39: note: 'exists' has been explicitly marked unavailable here
inline _LIBCPP_INLINE_VISIBILITY bool exists(const path& __p) {
                                      ^
/opt/QGIS/qgis-deps-dev/build/pdal/PDAL-2.4.2-src/pdal/util/FileUtils.cpp:205:23: error: 'path' is unavailable: introduced in macOS 10.15
    return fs::exists(toNative(dirname));


```

**Comment by hobu** [comment]
PDAL requires C++17 as of 2.4.0. OSX doesn't provide C++17 `<filesystem>` support until OSX 10.15. There are ways to work around it, but we're not very excited to muck up the code. I didn't find an unintrusive way to get it without a bunch of yucky `#ifdef`. 

Is this for official QGIS builds?

**Comment by 3nids** [comment]
Thanks for the quick response.

Yes, this is to build dependencies for QGIS official packages.

**Comment by pdal-docs** [comment]
I’ll try to get you a patch tomorrow

**Comment by hobu** [comment]
How far back of deployment target must you go @3nids ?

**Comment by hobu** [comment]
I was hoping this would just be an `#ifdef` to use `<experimental/filesystem>` but that isn't sufficient in this case. Rolling all the way back to our embedded boost filesystem code isn't an answer either. We're kind of stuck. What `OSX_DEPLOYMENT_TARGET` must you meet?

**Comment by hobu** [comment]
Ok, I have a solution for you that will work but I don't want to include in a release. If we use https://github.com/gulrak/filesystem for the filesystem implementation, things should work. Grab the https://github.com/PDAL/PDAL/tree/gulrak-filesystem branch which is based on `2.4-maintenance` to get going and please report back any issues.

**Comment by 3nids** [comment]
@hobu it built fine, thanks a lot!
I am target 10.13 at the moment, but I guess we can increase to 10.15 in some time if it is required.
