### PR TITLE
Changes to allow things to work with GDAL 2.2

### PR DESCRIPTION
**Pull request by abellgithub**

### CODE REVIEW

**Comment by abellgithub** [comment]
Still need to change the required version in cmake.

**Comment by hobu** [comment]
Oops, I shouldn't have merged yet I guess. It's in master now though.

```
../pdal/GDALUtils.cpp: In function 'OGRErr pdal::oldgdalsupport::createFromWkt(const char*, OGRSpatialReference*, OGRGeometry**)':
../pdal/GDALUtils.cpp:724:9: error: 'STARTS_WITH_CI' was not declared in this scope
     if( STARTS_WITH_CI(szToken, "POINT") )
         ^~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:738:22: error: expected type-specifier before 'OGRTriangle'
         poGeom = new OGRTriangle();
                      ^~~~~~~~~~~
../pdal/GDALUtils.cpp:758:22: error: expected type-specifier before 'OGRCircularString'
         poGeom = new OGRCircularString();
                      ^~~~~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:762:22: error: expected type-specifier before 'OGRCompoundCurve'
         poGeom = new OGRCompoundCurve();
                      ^~~~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:766:22: error: expected type-specifier before 'OGRCurvePolygon'
         poGeom = new OGRCurvePolygon();
                      ^~~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:770:22: error: expected type-specifier before 'OGRMultiCurve'
         poGeom = new OGRMultiCurve();
                      ^~~~~~~~~~~~~
../pdal/GDALUtils.cpp:774:22: error: expected type-specifier before 'OGRMultiSurface'
         poGeom = new OGRMultiSurface();
                      ^~~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:779:22: error: expected type-specifier before 'OGRPolyhedralSurface'
         poGeom = new OGRPolyhedralSurface();
                      ^~~~~~~~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:784:22: error: expected type-specifier before 'OGRTriangulatedSurface'
         poGeom = new OGRTriangulatedSurface();
                      ^~~~~~~~~~~~~~~~~~~~~~
../pdal/GDALUtils.cpp:802:21: error: 'class OGRGeometry' has no member named 'hasCurveGeometry'; did you mean 'OGRGeometry'?
         if( poGeom->hasCurveGeometry() &&
                     ^~~~~~~~~~~~~~~~
                     OGRGeometry
../pdal/GDALUtils.cpp:803:13: error: 'CPLTestBool' was not declared in this scope
             CPLTestBool(CPLGetConfigOption("OGR_STROKE_CURVE", "FALSE")) )
             ^~~~~~~~~~~
../pdal/GDALUtils.cpp:803:13: note: suggested alternative: 'CSLTestBoolean'
             CPLTestBool(CPLGetConfigOption("OGR_STROKE_CURVE", "FALSE")) )
             ^~~~~~~~~~~
             CSLTestBoolean
../pdal/GDALUtils.cpp:805:46: error: 'class OGRGeometry' has no member named 'getLinearGeometry'
             OGRGeometry* poNewGeom = poGeom->getLinearGeometry();
                                              ^~~~~~~~~~~~~~~~~

```
